name: release-semver-action
description: A github action that creates a release, by automatically handling the semantic versioning.
author: Justin Elmore

branding:
  color: green
  icon: check-circle

inputs:
  release_type:
    description: The semantic version change type. Accepted values are major, minor, patch
    required: false
    default: patch

  tag_name:
    description: Override the version by passing in the desired version.
    required: false

  move_major_version_tag:
    description: Automate moving the major version tag.
    required: false
    default: "false"

  commit_message:
    description: |
      The commit message. You can customize your message and use `$version` as a variable
      of the version changes
    required: false
    default: "Bump version to $version"

  git_tag_prefix:
    description: The prefix for your git tags.
    default: "v"
    required: true

  show_git_tag_prefix:
    description: Whether or not the versions show the git tag prefix in the changelog.
    default: "false"
    required: false

  update_package_json:
    description: Bump the version in `package.json`.
    required: false
    default: "false"

  changelog_file:
    description: Path to the changelog file.
    default: "CHANGELOG.md"
    required: false

  set_changelog_version:
    description: Bump unreleased changes in the changelog.
    default: "false"
    required: false

  release_notes_from_changelog:
    description: Use the latest version in the changelog to use as the release notes.
    default: "false"
    required: false

  release_name:
    description: The name of the release. Defaults to the tag.
    required: false

  body:
    description: The contents of your release. Optional, if  not set, it will generate the release notes.
    required: false

  auto_version:
    description: Auto bump
    required: false
    default: "false"

  token:
    description: The secret value from your GITHUB_TOKEN or another token to access the GitHub API. Defaults to the token at `github.token`
    required: true
    default: ${{ github.token }}

runs:
  using: node20
  main: ./dist/index.js
