name: Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        type: "string"
        default: ""
        required: false
  push:
    branches:
      - main
    paths:
      - "changelog/*"
      - "**/changelog.yml"
      - "CHANGELOG.md"

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: read

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Generate Changelog
        uses: jelmore1674/build-changelog@main
        with:
          show_author_full_name: true
