name: Enforce Changelog

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: write

jobs:
  enforce-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Get latest tag
        run: echo "LATEST_TAG_SHA=$(git rev-parse $(git describe --tags --abbrev=0)) >> GITHUB_ENV"

      - uses: jelmore1674/build-changelog/enforcer@v1
        if: ${{ env.LATEST_TAG_SHA == github.sha }}
        with:
          skip_labels: ops,maintenance,docs
          enable_dependabot: true
          dependabot_labels: dependencies
          comment_on_pr: true
          show_author_full_name: true
