name: Enforce Changelog

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: write

jobs:
  get_latest_tag_sha:
    runs-on: ubuntu-latest
    outputs:
      LATEST_TAG_SHA: ${{ steps.get_tag.outputs.LATEST_TAG_SHA }}
    steps:
      - uses: actions/checkout@v4
      - name: Get tags
        run: git fetch --tags origin
      - name: Get latest tag
        id: get_tag
        run: echo "LATEST_TAG_SHA=$(git tag --points-at HEAD) >> GITHUB_OUTPUT"

  enforce-changelog:
    needs: get_latest_tag_sha
    if: ${{ needs.get_latest_tag_sha.outputs.LATEST_TAG_SHA == '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - uses: jelmore1674/build-changelog/enforcer@v1
        with:
          skip_labels: ops,maintenance,docs
          enable_dependabot: true
          dependabot_labels: dependencies
          comment_on_pr: true
          show_author_full_name: true
