name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: The semver release type
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major

      tag:
        description: Release Tag
        type: string
        required: false

      release_name:
        description: The release name.
        type: string
        required: false

      update_package_json:
        description: Update the package.json version.
        type: boolean
        default: true

      move_major_version_tag:
        description: Move the major version tag.
        type: boolean
        default: true

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Version for Unreleased
        id: changelog
        uses: jelmore1674/build-changelog@main
        with:
          release_type: ${{ inputs.release_type }}
          version: ${{ inputs.tag }}

      - name: Create Release
        id: create_release
        uses: ./
        env:
          NOTES: ${{ steps.changelog.outputs.notes }}
        with:
          release_type: ${{ inputs.release_type }}
          tag_name: ${{ steps.changelog.outputs.release_version || inputs.tag }}
          release_name: ${{ inputs.release_name || inputs.tag }}
          body: ${{ env.NOTES }}
          move_major_version_tag: ${{ inputs.move_major_version_tag }}
          update_package_json: ${{ inputs.update_package_json }}
