name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: The semver release type
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major

      tag:
        description: Release Tag
        type: string
        required: false

      release_name:
        description: The release name.
        type: string
        required: false

      update_package_json:
        description: Update the package.json version.
        type: boolean
        default: true

      move_major_version_tag:
        description: Move the major version tag.
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load secret
        id: load-op
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GPG_KEY: op://Actions/shared/GPG_KEY
          GPG_PASSPHRASE: op://Actions/shared/GPG_PASSPHRASE
          GH_APP_KEY: "op://Actions/GH_APP_KEY/private key"
          APP_ID: op://Actions/shared/APP_ID

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ steps.load-op.outputs.APP_ID }}
          application_private_key: ${{ steps.load-op.outputs.GH_APP_KEY }}
          revoke_token: true

      - name: Set Version for Unreleased
        id: changelog
        uses: jelmore1674/build-changelog@main
        with:
          release_type: ${{ inputs.release_type }}
          version: ${{ inputs.tag }}
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Create Release
        id: create_release
        uses: ./
        env:
          NOTES: ${{ steps.changelog.outputs.notes }}
        with:
          release_type: ${{ inputs.release_type }}
          tag_name: ${{ steps.changelog.outputs.release_version || inputs.tag }}
          release_name: ${{ inputs.release_name || inputs.tag }}
          body: ${{ env.NOTES }}
          move_major_version_tag: ${{ inputs.move_major_version_tag }}
          update_package_json: ${{ inputs.update_package_json }}
          token: ${{ steps.get_workflow_token.outputs.token }}
