name: Release

on:
  schedule:
    - cron: "24 4 * * 2"

  workflow_dispatch:
    inputs:
      release_type:
        description: The semver release type
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major

      tag:
        description: Release Tag
        type: string
        required: false

jobs:
  get_latest_tag_sha:
    runs-on: ubuntu-latest
    outputs:
      LATEST_TAG_SHA: ${{ steps.get_tag.outputs.LATEST_TAG_SHA }}
    steps:
      - uses: actions/checkout@v4
      - name: Get tags
        run: git fetch --tags origin
      - name: Get latest tag
        id: get_tag
        run: echo "LATEST_TAG_SHA=$(git tag --points-at HEAD) >> GITHUB_OUTPUT"

  release:
    needs: get_latest_tag_sha
    if: ${{ needs.get_latest_tag_sha.outputs.LATEST_TAG_SHA == '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load secret
        id: load-op
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GH_APP_KEY: "op://Actions/GH_APP_KEY/private key"
          APP_ID: op://Actions/shared/APP_ID

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ steps.load-op.outputs.APP_ID }}
          application_private_key: ${{ steps.load-op.outputs.GH_APP_KEY }}
          revoke_token: true

      - name: Create Release
        id: create_release
        uses: ./
        with:
          auto_version: true
          tag_name: ${{ inputs.tag }}
          release_name: ${{ inputs.tag }}
          move_major_version_tag: true
          update_package_json: true
          set_changelog_version: true
          release_notes_from_changelog: true
          token: ${{ steps.get_workflow_token.outputs.token }}
          commit_message: Bump version $version [skip ci]
